name: Terraform

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0  # Specify your Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        id: plan

      - name: Upload Terraform Plan as artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: terraform.tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
